### ISSUE TITLE
HelmRelease pods being created in `gotk-system` instead of targetNamespace in 0.1.2

### ISSUE THREAD

**Issue by allymparker** [fluxcd/helm-controller#101]
I've just been trying to upgrade to gotk version 0.1.2. My configuration was working in alpha 1.

I'm trying to deploy nginx-ingress Helm chart into `targetNamespace: foo`, however, `controller` and `default-backend` the pods are being created in the `gotk-system` ns.

I've [created a sample repo](https://github.com/allymparker/gotk-nginx-sample) for repro.

Below is what I see in terminal:

![image](https://user-images.githubusercontent.com/2056009/94944730-93d7c700-04d1-11eb-8563-5f82022abd17.png)

**Comment by hiddeco** [comment]
Thanks for being swift in trying out the `v0.1.0`. :sunflower: 

Have confirmed the bug (introduced by c526837d768944e6a9615b95f5096deae5710294), and am preparing a patch now.

**Comment by hiddeco** [comment]
@allymparker release is building, bumping the image tag to `v0.1.1` as soon as it is available should resolve the issue. Toolkit release with the proper version will follow (but likely not before tomorrow).

Thanks again for reporting the issue, and enjoy your weekend :beers:
