### ISSUE TITLE
HelmRelease deletion not waiting for `helm uninstall`

### ISSUE THREAD

**Issue by cwrau** [fluxcd/helm-controller#1021]
### Describe the bug

When you delete a HelmRelease, even with `uninstall.deletionPropagation=foreground`, flux, via helm or otherwise, marks all created resources to be deleted and then removes the finalizer, resulting in the HelmRelease disappearing even though the uninstallation hasn't finished.

This, at least sometimes, leaves the "real" helm release to be stuck in `uninstalling` which has to be manually resolved.

### Steps to reproduce

Create a helm chart like https://github.com/teutonet/teutonet-helm-charts/tree/main/charts/t8s-cluster, which creates CRs that are not just "no-ops" for deletion, like cluster-api resources.

Install it, wait for everything to be ready, uninstall.

### Expected behavior

That flux leaves the finalizer on the HelmRelease until the "real" helm release is really uninstalled.

I suppose what I mean in a non-flux way would be for flux to wait until `helm uninstall` finishes successfully.

### OS / Distro

N/A

### Flux version

N/A

### Flux check

► checking prerequisites
✗ Kubernetes version v1.27.14 does not match >=1.28.0-0
► checking version in cluster
✔ distribution: flux-2.3.0
✔ bootstrapped: true
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v1.0.1
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.38.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.32.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.3.0
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.3.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.3.0
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta3
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1
✔ helmreleases.helm.toolkit.fluxcd.io/v2
✔ helmrepositories.source.toolkit.fluxcd.io/v1
✔ imagepolicies.image.toolkit.fluxcd.io/v1beta2
✔ imagerepositories.image.toolkit.fluxcd.io/v1beta2
✔ imageupdateautomations.image.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta3
✔ receivers.notification.toolkit.fluxcd.io/v1
✗ check failed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

// "moved" from https://github.com/fluxcd/flux2/issues/4872

**Comment by cwrau** [comment]
I've tried debugging this, and [this line](https://github.com/fluxcd/helm-controller/blob/7f78cdc36836f0ff3b652e518550932c9e890560/internal/reconcile/uninstall.go#L141) is the root cause.

Because the digest seems to change during the uninstall, which in fact returns an error, that error is not returned, helm-controller thinks it finished without an error and removes the finalizer, therefore removing the HelmRelease.

Is there a reason for the digest check? I would just open a PR removing that, if that's ok?

**Comment by stefanprodan** [comment]
> Because the digest seems to change during the uninstall

Why would it change? Are you using GitRepo as the source of the HelmRelease?

**Comment by cwrau** [comment]
@stefanprodan, ah, I think I've found it;

During helm uninstall, after [changing the info](https://github.com/helm/helm/blob/5b0898513820e5952e0293b81fd098429f0e394f/pkg/action/uninstall.go#L103-L105) helm [updates the release](https://github.com/helm/helm/blob/5b0898513820e5952e0293b81fd098429f0e394f/pkg/action/uninstall.go#L118)

After the update, [flux notifies itself on the HelmRelease object about the history "change"](https://github.com/fluxcd/helm-controller/blob/89a6f497e55b1f488acf3d1e8f473be4374a3886/internal/storage/observer.go#L98)

During the [observation](https://github.com/fluxcd/helm-controller/blob/b830e0812280e94f5db731ae29e0feb709777236/internal/reconcile/uninstall.go#L224), [`ObservedToSnapshot` calculates a new Digest](https://github.com/fluxcd/helm-controller/blob/56b5f14b344cdc739f14164c03cd76b94a348fe2/internal/release/observation.go#L160) with the updated info, which of course changes the digest

I hope I didn't miss anything 😅

**Comment by cwrau** [comment]
Is there any news on this? Maybe my PR, #1024, is even acceptable?

Would be great to have this fixed 😊

**Comment by cwrau** [comment]
Ola, is there something I can do to help get this resolved? Do you need more information?

**Comment by stefanprodan** [comment]
@cwrau we've talked about removing check in a dev meetings and the conclusion was that it's safe to do so. For the PR to be merged you'll need to adapt the unit tests.
