### ISSUE TITLE
integrity failure: computed digest doesn't match

### ISSUE THREAD

**Issue by antonosmond** [fluxcd/helm-controller#1056]
Hi 👋 

We're regularly seeing errors like this from the helm-controller and I'm not really sure why:
```
{"level":"error","ts":"2024-08-29T07:49:38.302Z","msg":"Reconciler error","controller":"helmrelease","controllerGroup":"helm.toolkit.fluxcd.io","controllerKind":"HelmRelease","HelmRelease":{"name":"event-bus-consumer","namespace":"flux-system"},"namespace":"flux-system","name":"event-bus-consumer","reconcileID":"d040e9db-b62b-4564-a1bb-22ed3560fab1","error":"integrity failure: computed digest doesn't match 'sha256:503d435f5c4caf6708bf8fee6675a5008188da10d02ebc64847ab964389c953d'"}
```
I did some googling and searching GitHub issues and couldn't find anything. The closest thing I found was [this](https://github.com/fluxcd/source-controller/issues/610) however I'm not sure if that's related or not.

# Flux Version

```
flux: v2.3.0
distribution: flux-v2.3.0
helm-controller: v1.0.1
image-automation-controller: v0.38.0
image-reflector-controller: v0.32.0
kustomize-controller: v1.3.0
notification-controller: v1.3.0
source-controller: v1.3.0
```

**Comment by rlaflamme** [comment]
Same here recently

**Comment by stefanprodan** [comment]
Has source-controller restarted before these error messages? Is source-controller configured with a PVC?

**Comment by rlaflamme** [comment]
> Has source-controller restarted before these errors occurred? Is source-controller configured with a PVC?

Yes.  I thing the issue occured after the source-controlller has been restarted.  

I just look at it and everything is fine, now

Thank you @stefanprodan for your input

**Comment by stefanprodan** [comment]
This should be fixed once you update the HelmReleases to v2 and the controllers to Flux 2.4
