### ISSUE TITLE
Can i use HelmRelease CRD to reconcile Helm Controller itself ?

### ISSUE THREAD

**Issue by vijaySamanuri** [fluxcd/helm-controller#158]
I am not sure whether this is possible or not currently. But i am just curious about this possibility :
Can i use `HelmRelease`, `HelmChart` & `HelmRepository` CRDs for installing and reconciling Helm controller itself. 
I just checked the generation manifests in the fleet repo and found that `Kustomization` CRD yaml is being used to install & reconcile all `gotk` components. 
Can i change it to HelmRelease for Helm controller (assume i have a helm chart) and get rid of bootstrap upgrade process ?

**Comment by stefanprodan** [comment]
No this is not possible as Helm doesn't support CRDs updates. On upgrade, Helm will deploy the new controller image without the CRDs resulting in a broken flux2 deployment.

**Comment by vijaySamanuri** [comment]
Thanks @stefanprodan for quick clarification :+1:
