### ISSUE TITLE
Support GitRepositories in valuesFrom

### ISSUE THREAD

**Issue by mikesir87** [fluxcd/helm-controller#175]
I'm working to build a multi-tenant setup in which each tenant will be using the same Helm chart to deploy their apps, but with different values. As a platform team, we're trying to minimize the amount of stuff each of them need to know, especially when it comes to Kubernetes manifests. So, we're looking at the ability to tell a team "Here's a YAML document, update here to deploy your new version." Each of the teams have their own repos with this values file.

In case it helps provide additional context, we're working to standardize our platform efforts around the Compose spec. We've built a Helm chart that consumes a Compose file as its `values.yaml` and creates the appropriate manifests. We also support various extension fields for additional support around ingress, cert management, secrets injection, etc. This gives us the flexibility to change our mind down the road if we want to leave Kubernetes and use something else... just re-implement the deploy tool. We'd also love to support the ability for anyone to simply run `docker-compose -f my-compose-file.yaml up` and spin up a very similar stack locally (obviously some of the extensions won't work).

## Feature Request

It would be great to be able to define a `HelmRelease` in which the values come from a specific file(s) located in a `GitRepository`. I'd like the ability to specify a specific `GitRepository` and then the specific file within it.

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: backend
  namespace: default
spec:
  chart:
    # omitted
  valuesFrom:
    - kind: GitRepository
      name: tenant-repo
      path: ./values.yaml
```

## Current Workarounds

I've thought of two different approaches to work around this, each with their drawbacks.

1. Each team would define their own `HelmRelease` object with the values embedded in it. This has the downside of now each team is in charge of that object and is exposed to the fact we're using Kubernetes. We also then don't have a file that is Compose spec-compatible.
1. We could use a Kustomize controller to take the values file and convert it into a `ConfigMap`, which then is referenced in the `valuesFrom`. It just feels like overkill and would require each repo to have a `kustomization.yaml`. Not end of the world, but feels hacky if we can't reference the file directly.

Between the two workarounds, I'd prefer the later, but it would be great to be able to reference the values file directly. Feedback welcome!

**Comment by hiddeco** [comment]
[This was requested before but rejected](https://github.com/fluxcd/flux2/discussions/100#discussioncomment-121812), their reasoning was a bit different, but the arguments still stand.

> We could use a Kustomize controller to take the values file and convert it into a `ConfigMap`, which then is referenced in the `valuesFrom`. It just feels like overkill and would require each repo to have a `kustomization.yaml`. Not end of the world, but feels hacky if we can't reference the file directly.

This would be the best alternative.

**Comment by stefanprodan** [comment]
Docs here on how to use kustomize configmap generators for HR values: https://toolkit.fluxcd.io/guides/helmreleases/#refer-to-values-in-configmaps-generated-with-kustomize

**Comment by mikesir87** [comment]
Ok. Thanks for the pointers! And sorry for not seeing the previous discussion... I'm not used to checking both issues (which I did) and the new discussion area before posting. 👍
