### ISSUE TITLE
Use existing HelmChart resource in a HelmRelease

### ISSUE THREAD

**Issue by mattarmstrong** [fluxcd/helm-controller#204]
Each HelmRelease automatically creates a corresponding HelmChart object and it looks like a separate tarball gets downloaded for each HelmChart object. This seems like an inefficient use of storage if multiple HelmReleases use the same chart & version because multiple identical tarballs are being downloaded.

Is there a way to manually create a shared HelmChart object and reference it from multiple HelmReleases?

**Comment by hiddeco** [comment]
Is your wish to share a chart within the same namespace, or across namespaces?

**Comment by mattarmstrong** [comment]
probably both, but at first within the same namespace

**Comment by jonathan-innis** [comment]
@hiddeco If this is being taken, would like to pick this one up

**Comment by hiddeco** [comment]
Before you start working on this, I would really like to see an outline of the planned and/or proposed changes to the `HelmRelease` API.

**Comment by JaneLiuL** [comment]
Any update for this issue? I would like to enhance this issue~~

**Comment by mdufourneaud** [comment]
Hello !
This subject interests me too.
I manage several (≃100) instances that are all using the same Helm chart, and I think that using the same HelmChart resource would reduce the global time of reconciliation.

**Comment by hiddeco** [comment]
This is in the pipeline to be addressed in combination with #789. You can expect it to become available in next-next minor, or if you are really lucky, next minor scheduled for December.
