### ISSUE TITLE
is valuesFile in a helm release spec also working with a git source?

### ISSUE THREAD

**Issue by cr-infront** [fluxcd/helm-controller#221]
I am trying to use valuesFile in a helm release definition using other values file for staging env but this doesn't seem to work with a git source? Where is he expecting the file? Do I have to give a path relative to the root of the git source or relative to the chart path wich I specify? Tried all but nothing worked...

**Comment by hiddeco** [comment]
The `valuesFile` does work with a `GitRepository` source, and the path is expected to be relative to the root of the source. Your `source-controller` needs to be `>=0.8.0`, due to a bug, see: https://github.com/fluxcd/source-controller/blob/main/CHANGELOG.md#080

**Comment by cr-infront** [comment]
Thank you, got it working, the problem on my side was that he really wanted to have a values.yml also. Thought it would work only by specifiying my special "valuesFile". Closing the issue.
