### ISSUE TITLE
post-install hooks are not executed after resources were posted

### ISSUE THREAD

**Issue by stoetti** [fluxcd/helm-controller#249]
If a Helm-chart defines a post-install hook the controller does not execute the job after the resources were loaded into kubernetes. Instead the controller waits for all resources to be available (e.g. all pods of the deployments are ready) until it executes the post-install jobs.

The chart I am using needs the post-install jobs to run in order for the pods to successfully start. For my case a workaround by setting disableWait to true which tells the controller to execute the jobs.

From my understanding the specification of the chart hook "post-install" states that it shall be executed after the resources were loaded and not after they become ready?

**Comment by hiddeco** [comment]
Helm does execute post-install hooks after it has waited for resources to become ready, see their logic here: https://github.com/helm/helm/blob/a499b4b179307c267bdf3ec49b880e3dbd2a5591/pkg/action/install.go#L348-L364

If this does not work for the chart you are working with, `spec.disableWait` is the right solution.

**Comment by stoetti** [comment]
I see but from the documentation my understanding was different, so I go with the custom spec.
