### ISSUE TITLE
Can't fetch chart version

### ISSUE THREAD

**Issue by ywyt738** [fluxcd/helm-controller#264]
helm repo: https://bitnami-labs.github.io/sealed-secrets/
chart name: sealed-secrets
version 1.15.0-r3

semver expression: ">=1.15.0 <1.16.0", "1.15.x", "1.15.x-x" or ">1.15 <1.16"
The above expressions can't fetch the chart version.

It's ok that I used fixed version '1.15.0-r3'

**Comment by stefanprodan** [comment]
Please read the semver spec here https://semver.org/

TLDR: 1.15.0-r3 is a prerelease so you need to include those in the range e.g. `>1.0.0-1`, see the sealed secrets docs here https://fluxcd.io/docs/guides/sealed-secrets/#deploy-sealed-secrets-with-a-helmrelease
