### ISSUE TITLE
HelmRelease dependsOn race condition during upgrades

### ISSUE THREAD

**Issue by kewats** [fluxcd/helm-controller#276]
I have two HelmReleases, one for running db migrations and the other for deploying an application. Let's say these charts are named `migrate-dbs` and `application`.

I have configured `application` to have a `dependsOn` config to make sure it waits until `migrate-dbs` is done.

This works perfectly fine during initial installs.

```
NAME                READY     STATUS                                          AGE
migrate-dbs         Unknown   Reconciliation in progress                      15m
application         False     dependency 'default/migrate-dbs' is not ready   15m
```

However, during incremental upgrades (bumping up chart versions for both of these), we see a race condition. 

```
NAME                READY     STATUS                                          AGE
migrate-dbs         Unknown   Reconciliation in progress                      22m
application         Unknown   Reconciliation in progress                      22m
migrate-dbs         Unknown   Reconciliation in progress                      22m
application         False     dependency 'default/migrate-dbs' is not ready   22m
```

Looks like when reconciliation for both of these HelmReleases get triggered, `application` HR looks at the status of last deployed version of `migrate-dbs` and kicks off. 
By the time the unmet dependency is correctly figured out, the objects being deployed by `application` are already set in motion.

Are we missing some logic that would check for upstream HelmRelease version or commit ref to make this reliable?

**Comment by hiddeco** [comment]
> Note that this does not account for upgrade ordering. Kubernetes only allows applying one resource (HelmRelease in this case) at a time, so there is no way for the controller to know when a dependency HelmRelease may be updated. [..]

https://fluxcd.io/docs/components/helm/helmreleases/#helmrelease-dependencies

Judging by the limited amount of information you shared, it seems that the `application` and `migrate-dbs` are closely coupled and would thus be better of bundled as a single chart, while [making use of Helm hooks](https://helm.sh/docs/topics/charts_hooks/) to properly run the migration together with the upgrade.

**Comment by kewats** [comment]
Thanks @hiddeco for your inputs. Let me add some more details on my use case.
I have more than one chart, say, `application1`, `application2`, etc. These have deployments with n replicas each.

Every time, I push out code to production, I need to make sure `migrate-dbs` runs through to completion. This is needed as it applies schema, config changes to the database. This database is used by multiple applications.

Let's say, my current version of code is `0.1.0` for both migrate-dbs and application(s). If I go to `0.1.1`, I need to make sure `migrate-dbs` upgrades itself to `0.1.1` first. After this, `application`(s) should upgrade to make sure they don't start off with old state of db.

While hooks could work one to one dependencies, I am running into some trouble since multiple of my charts would need to depend on one HelmRelease.

Any thoughts? Let me know if any more information is needed. Thanks!

**Comment by hiddeco** [comment]
Still think it would need solving from within, or through restructuring.

One option I see is making the `migrate-dbs` idempotent and bundle it with every `application[n]`. This way, whatever release is first performs the database migration, while all subsequent releases will be a no-op.

Given you now manage the `migrate-dbs` as part of every release, they would all require a dependency bump and new chart version, ensuring they all upgrade and start off with a new database state.
