### ISSUE TITLE
helm release stuck at Helm uninstall failed after deleting

### ISSUE THREAD

**Issue by yawboateng** [fluxcd/helm-controller#288]
So I deleted a helm release to try and clean install. Delete was successful but now the new install is stuck at:

```helm
beginning wait for 2 resources with timeout of 1m0s
  Normal  error  4m7s  helm-controller  Helm uninstall failed: uninstall: Release not loaded: dev: release: not found

Last Helm logs:
  Normal  error  4m7s                 helm-controller  reconciliation failed: Helm uninstall failed: uninstall: Release not loaded: dev: release: not found
  Normal  error  80s (x16 over 4m7s)  helm-controller  reconciliation failed: previous release attempt remediation failed
```

**Comment by hiddeco** [comment]
Can you provide the exact steps in which you deleted the Helm release? Did you delete the release using `helm`, or did you delete the `HelmRelease` and have it reapplied? This would help me isolate and/or explain the potential issue.

**Comment by yawboateng** [comment]
it looks like this was related to duplicate in the helm files, we can close
