### ISSUE TITLE
Coordination of HelmChart and HelmRelease updates

### ISSUE THREAD

**Issue by seaneagan** [fluxcd/helm-controller#3]
With HelmRelease.chart content being extracted into source-controller HelmChart CRD, if there are changes to e.g. HelmRelease.values and e.g. HelmChart.version, these two updates are no longer atomic (separate resources), so seems like whichever update happens first may not be successful if it depends on the other. Seems like to rectify this one would need to treat HelmCharts as immutable and rather than update them, instead create and reference new ones (and ideally delete old ones) when using a new chart version. Is there a way to automate this workflow? Similar problem exists with e.g. ConfigMaps and Secrets referenced by PodTemplates, what solutions exist there?

**Comment by seaneagan** [comment]
Agree, backward compatible changes shouldn't be much of an issue. Backward incompatible changes e.g. 1.2.3 > 2.0.0 if semver is being strictly followed is more what I'm thinking about. For example, assume one wants to update to a new Chart version where a values.yaml field has been renamed. This requires an update to the corresponding values override in the HelmRelease and the chart version in the HelmChart. If the HelmChart update is reconciled first (generating a new helm release revision), then it will expect the new field name but the HelmRelease still has the override for the old name. And the reverse scenario if the HelmRelease is reconciled first. The Helm 3 values.schema.yaml could help in this particular case, by making such failures less impactful (schema error rather than incorrect applied configuration), but that depends on chart authors implementing this. Chart authors can also provide migration paths by e.g. supporting a new field name and old field name for a while before removing the old name, but this also depends on chart authors implementing this, and chart users implementing a two-step update when they really only want one, and if they are not doing full on continuous delivery, their release windows may not allow them two steps. Another worry is that the reconciliations may occur in a certain order in a dev environment and pass testing, and then in the other order in prod, and fail. Perhaps failures won't be as prevalent as I am imaging, but just wanted to put this on the radar.

A similar scenario would exist today with ConfigMap / Secret values overrides, except that the Helm Operator doesn't reconcile releases when those are updated, and instead requires some update to the HelmRelease itself: https://github.com/fluxcd/helm-operator/issues/151

**Comment by stefanprodan** [comment]
Coordination between a chart and its values can be achieved by implementing #4

**Comment by seaneagan** [comment]
I see, that seems like a good approach for some cases, but may not be an option in some others:

1. If one doesn't control the source of the charts they are using
2. If values overrides include secrets, those probably shouldn't be published inside the chart
3. If there are a large number of chart users / configurations, having a separate override file inside the chart for each isn't very scalable

**Comment by seaneagan** [comment]
This looks resolved by #10, thanks @hiddeco!
