### ISSUE TITLE
Set Remediation globally?

### ISSUE THREAD

**Issue by aperullo** [fluxcd/helm-controller#309]
Is there an environment variable or similiar that can be set on the helm-controller which sets changes the default remediation behavior? I want my charts to automatically uninstall and reattempt _periodically_ but _continuously_ on a failed installed, without necessarily having to specify it in every `HelmRelease` resource. Is this possible?

Separately, does `Interval` control the time between remediations?

Thank you

**Comment by hiddeco** [comment]
:wave: 

> Is there an environment variable or similiar that can be set on the helm-controller which sets changes the default remediation behavior?

No, `HelmRelease` objects are strictly declarative and free from assumptions outside the defaults defined in the specification. If you want to e.g. automatically apply certain configuration options as defaults, it would be better to do this using a Kustomize overlay which automatically patches `HelmRelease` kinds.

> Separately, does `Interval` control the time between remediations?

The interval controls the default duration between reconciles for a resource, assuming the reconcile operation did not return an error. In case of a returned error, it is retried with an exponential backoff.

**Comment by scottrigby** [comment]
Here is an example to show how to do what @hiddeco is talking about: https://github.com/fluxcd/flux2-kustomize-helm-example/

**Comment by aperullo** [comment]
Thank you for the quick response!
> No, HelmRelease objects are strictly declarative and free from assumptions outside the defaults defined in the specification

Ok that's a reasonable philosophy, I'll try the other approach.

> In case of a returned error, it is retried with an exponential backoff.

Great exactly what I was hoping! Unless I missed it may be worth mentioning the back-off in the HelmRelease crd doc. 

Thanks again!

**Comment by onedr0p** [comment]
Sorry to necro this issue but it would be great if this was reconsidered. I get patching the resource is the preferred way but it is really cumbersome when you have a ton of `HelmReleases` in your cluster across separate namespaces and you want enforce a default across all of them.
