### ISSUE TITLE
Will the status of the helm release change according to the pod status?

### ISSUE THREAD

**Issue by FogDong** [fluxcd/helm-controller#311]
I noticed that only with all the pods running in my chart would the helm release status become true.
But I can't find the relevant explanation in the documentation so it's a little bit confusing.

Will the status of the helm release change according to the pod status?🤔

**Comment by hiddeco** [comment]
No, it will change according to the outcome of the release, and depending on the configuration, this may be in relationship to the Pod's health.

By default, the controller performs an `helm <install|upgrade> --wait` (which can be disabled using `disableWait`), which will indeed correlate with the Pod their Ready state in most cases :-).

**Comment by FogDong** [comment]
Thank you for your quick answer :)

/close
