### ISSUE TITLE
HelmRelease Remote Config Not Working Properly When Missing flux-system Namespace

### ISSUE THREAD

**Issue by asummers** [fluxcd/helm-controller#320]
We have two "classes" of clusters that we manage with the `kubeConfig` block - one where we install things like ingress, monitoring and other tools, and then another where we install flux in the same mechanism. Working with Kustomizations is great here! 

Consider the example in the following repository: https://github.com/asummers/flux-bug-report/ -- nothing too fancy happening here, just two clusters spinning up, one as a management cluster and one as the tenant cluster, and applying 3 Kustomizations and 2 HelmReleases.

Specifically looking at https://github.com/asummers/flux-bug-report/blob/main/test.yaml#L49-L51 we see we use kubeconfig kustomizations remotely, and if we look at the remote cluster:

```
$ kubectl config use-context k3d-test-cluster
Switched to context "k3d-test-cluster".
$ kc get ns
NAME              STATUS   AGE
default           Active   83m
kube-system       Active   83m
kube-public       Active   83m
kube-node-lease   Active   83m
kuberhealthy      Active   83m
```

we see the `kustomization` applied successfully. 

```
$ kubectl config current-context
k3d-test-management-cluster
$ kubectl get ns
NAME              STATUS   AGE
default           Active   83m
kube-system       Active   83m
kube-public       Active   83m
kube-node-lease   Active   83m
flux-system       Active   82m
kuberhealthy      Active   82m
$ kubectl get kustomizations -A
NAMESPACE     NAME                                              READY   STATUS                                                                  AGE
flux-system   test-management-cluster-kuberhealthy-preinstall   True    Applied revision: kh-retries/2f85487aef54913614a95beb8361a475357a8107   82m
flux-system   test-cluster-kuberhealthy-preinstall              True    Applied revision: kh-retries/2f85487aef54913614a95beb8361a475357a8107   82m
flux-system   test-kuberhealthy                                 True    Applied revision: kh-retries/2f85487aef54913614a95beb8361a475357a8107   82m
```

This is as we expect. However if we look at the HelmRelease here we see a different story. 

```
$ kubectl config current-context
k3d-test-management-cluster
$ kubectl get kustomizations -A
NAMESPACE     NAME                                              READY   STATUS                                                                  AGE
flux-system   test-management-cluster-kuberhealthy-preinstall   True    Applied revision: kh-retries/2f85487aef54913614a95beb8361a475357a8107   82m
flux-system   test-cluster-kuberhealthy-preinstall              True    Applied revision: kh-retries/2f85487aef54913614a95beb8361a475357a8107   82m
flux-system   test-kuberhealthy                                 True    Applied revision: kh-retries/2f85487aef54913614a95beb8361a475357a8107   82m
asummers@wud-asummers01:~$ kubectl get helmreleases -n flux-system
NAME                                   READY   STATUS                             AGE
test-management-cluster-kuberhealthy   True    Release reconciliation succeeded   82m
test-cluster-kuberhealthy              False   Helm uninstall failed: uninstall: Release not loaded: kuberhealthy-test-cluster-kuberhealthy: release: not found

Last Helm logs:

                                       82m
```

Looking at `kubectl describe helmrelease test-cluster-kuberhealthy -n flux-system` we eventually get it complaining about 

```
    Message:               Helm uninstall failed: uninstall: Release not loaded: kuberhealthy-test-cluster-kuberhealthy: release: not found
```

with warnings about

```
Last Helm logs:


    Reason:                UninstallFailed
    Status:                False
    Type:                  Ready
    Last Transition Time:  2021-09-14T16:59:43Z
    Message:               Helm install failed: create: failed to create: namespaces "flux-system" not found
```
    
What is the expected behavior here? I would expect the remote cluster to not need `flux-system` or the `helm repository` CRD or anything. Looking at the HelmRelease, we don't seem to be referencing this anywhere besides the HelmRepository reference. https://github.com/asummers/flux-bug-report/blob/main/test/kuberhealthy/remote.yaml

I feel like this is a bug somewhere and it should work like the Kustomizations do on remote clusters. Let me know if I can provide any clarifying details.

**Comment by hiddeco** [comment]
The `targetNamespace` configured in the `HelmRelease` resource only defines where the manifests are installed, but does not control the storage namespace where the Helm secrets are stored (which can be controlled separately using `storageNamespace`).

The default behavior of the controller is then to use the namespace of the object as the `storageNamespace`, but this namespace does not exist on the remote cluster.

The solution is thus to define _both_ the `targetNamespace` and the `storageNamespace`, which makes it ignore the namespace of the object.

**Comment by asummers** [comment]
Interesting! That is probably worth calling out in the docs, especially in the context of remote clusters. 

Intuitively, in the context of "I am a platform administrator, I want to install stuff remotely onto tenant clusters", I would think the storageNamespace would be on the management cluster here. I feel like the tenant cluster should have now knowledge of helm or flux here. 

Changing the storageNamespace resolved my issue here, though, thank you!

**Comment by asummers** [comment]
Never mind, I see where this is addressed in the docs.
