### ISSUE TITLE
Helm date label format

### ISSUE THREAD

**Issue by Ikalinichev** [fluxcd/helm-controller#375]
Hi!

I'm using `date: {{ now | htmlDate }}` function to create a label with timestamp.
If I use helm 3.6.3 directly I get a format like '2021-12-09' and it works well.

When I use flux (0.24.0 ) 
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
it returns an error and renders the different format like 2021-12-09T00:00:00Z

the error:
invalid: metadata.labels: Invalid value: "2021-12-09T00:00:00Z": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue', or 'my_value', or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')

Same with `date: {{ now | date "2006-01-02" }}`

**Comment by hiddeco** [comment]
Have you tried enquoting the value itself to force it to a string value? E.g. `date: "{{ now | htmlDate }}"`.

**Comment by Ikalinichev** [comment]
I've just tried and it does work. 
Thanks
