### ISSUE TITLE
helmrelease status message: 'open /tmp/fluxcd-fluxcd-my-helm-app-1520979207.tgz: permission denied'

### ISSUE THREAD

**Issue by idealceo** [fluxcd/helm-controller#388]
application file:
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: app-helm
spec:
  components:
    - name: my-helm-app
      type: helm
      properties:
        chart: sc-ips-mp
        version: 1.1.6
        url: http://10.67.135.38:8080/csmrepo/csm
        repoType: helm
deploy above app file,encounter hr status is "open /tmp/fluxcd-fluxcd-my-helm-app-1520979207.tgz: permission denied"
helm-contrpoller verison: fluxcd/helm-controller:v0.14.0

[root@paas-controller:/home/pict]$ kubectl get hr   -n fluxcd                    
NAME          READY   STATUS                                                                  AGE
my-helm-app   False   open /tmp/fluxcd-fluxcd-my-helm-app-2406182578.tgz: permission denied   2d20h
[root@paas-controller:/home/pict]$ kubectl get helmchart   -n fluxcd
NAME                 CHART       VERSION   SOURCE KIND      SOURCE NAME   READY   STATUS                    AGE
fluxcd-my-helm-app   sc-ips-mp   1.1.6     HelmRepository   my-helm-app   True    Fetched revision: 1.1.6   2d20h
[root@paas-controller:/home/pict]$ kubectl get helmrepository   -n fluxcd
NAME          URL                                    READY   STATUS                                                                               AGE
my-helm-app   http://10.67.135.38:8080/csmrepo/csm   True    Fetched revision: 1d1b375093b4f43a937bfa34e3c036519d0d856a1796df81f34faab6243d3321   2d20h
[root@paas-controller:/home/pict]$ 

according helm-contrpoller Dockerfile，helm-controller process run by  user controller,but /tmp only user root

**Comment by kingdonb** [comment]
What environment is your Kubernetes cluster? There are some Kubernetes cluster environments that have special constraints on security contexts and what UIDs a container must run as, Flux will need special consideration for those.

We've got specialized documentation [for OpenShift](https://fluxcd.io/docs/use-cases/openshift/#security-context-constraints), for example, and I think there is another [special guidance for OpenShift on AWS (ROSA)](https://operatorhub.io/operator/flux) further down the Flux OperatorHub document, but I don't know if your issue is OpenShift or something else. I'm as of yet not aware of other Kubernetes environments that have a similar issue.

So, what kind of Kubernetes cluster environment are you running Flux on exactly?

**Comment by idealceo** [comment]
> What environment is your Kubernetes cluster? There are some Kubernetes cluster environments that have special constraints on security contexts and what UIDs a container must run as, Flux will need special consideration for those.
> 
> We've got specialized documentation [for OpenShift](https://fluxcd.io/docs/use-cases/openshift/#security-context-constraints), for example, and I think there is another [special guidance for OpenShift on AWS (ROSA)](https://operatorhub.io/operator/flux) further down the Flux OperatorHub document, but I don't know if your issue is OpenShift or something else. I'm as of yet not aware of other Kubernetes environments that have a similar issue.
> 
> So, what kind of Kubernetes cluster environment are you running Flux on exactly?

Thanks！Environment is Kubernetes cluster，Because of my k8s cluster have contraints on the emptyDir of volumes,  750 permission set the emptyDir of volumes，but 777 permission to GID. Sloved the problem by  container run as GID.

`                securityContext:
                  fsGroup: 1030
                  runAsGroup: 1030
                  runAsNonRoot: true
                  runAsUser: 1030
                serviceAccountName: sa-source-controller
                terminationGracePeriodSeconds: 10
                volumes:
                - emptyDir: {}
                  name: data
                - emptyDir: {}
                  name: tmp`
