### ISSUE TITLE
Error stating resource exists when it is not there.

### ISSUE THREAD

**Issue by snoopy82481** [fluxcd/helm-controller#390]
I'm receiving this following error in my flux deployment:
`2022-01-10T19:58:30.568Z error HelmRelease/vpn-gateway.vpn - Reconciler error Helm install failed: error while running post render on files: may not add resource with an already registered id: ~G_v1_ConfigMap|vpn|vpn-gateway-pod-gateway`

I have removed the Helm Release and remove the namespace all together, but the error continues to come up.

My deployment is linked here: [Helm Release](https://github.com/snoopy82481/new_template_k3s/blob/main/cluster/apps/networking/vpn-gateway/helm-release.yaml)

`flux version 0.24.1`
kubectl version
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5+k3s1", GitCommit:"405bf79da97831749733ad99842da638c8ee4802", GitTreeState:"clean", BuildDate:"2021-12-18T00:43:30Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}```

**Comment by stefanprodan** [comment]
The `may not add resource with an already registered id` tells you that you have a duplicate resource in your chart.

**Comment by snoopy82481** [comment]
I looked over the chart, mind you it isn't mine, but I don't see a duplicate entry.  I'll double check the other issue and get with the chart owners.

**Comment by snoopy82481** [comment]
Issue was the way the helm chart needed namespaces.
