### ISSUE TITLE
Private HelmRepository on GitHub

### ISSUE THREAD

**Issue by blafry** [fluxcd/helm-controller#398]
Hi,
Im wondering, how can I authorize a private helm repository on GitHub?

For git repository, the object takes a `SecretRef` which can be referenced as secret with the fields `identity`, `identity.pub` and `known_hosts`. As described [here](https://fluxcd.io/docs/components/source/gitrepositories/#specification).

However, in the case of helm repository, `SecretRef` allows you to mount the secret with authorization via HTTP/S basic auth or TLS. [Specification](https://fluxcd.io/docs/components/source/helmrepositories/#specification).

What if I want to use the ssh key? It is possible?

**Comment by serrovsky-pt** [comment]
@blafry  Did you manage how to do it?

**Comment by pjbgf** [comment]
duplicate of https://github.com/fluxcd/source-controller/issues/548.
