### ISSUE TITLE
flux v1 to v2

### ISSUE THREAD

**Issue by 95438** [fluxcd/helm-controller#411]
Hello,
   Trying to migrate from flux v1 to v2. 
In flux v1, all my apps and infra compoenents were deployed by flux as hemreleases (from git.path=/helm) of my infra repo.
I'm struggling to get flux v2 to deploy the helmreleases into my cluster.
Still unclear about  the layout should be? 
1) i bootstrapped fluxv2 using my infra repo app-mkt-infra repo)  i plan to use the same repo to to host  my apps/infrastructure helm charts in this same repo.
2) to begin with i created a helmrelease for my infrastructure component ( kong) using the same SourceRef(config repo) which is used to bootstrap flux. here's the helmrelease definition. this definition is saved as kong.yaml in clusters/production/flux-system/kong.yaml.
in kustomization.yaml, i added kong.yaml as the resource.

---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kong
  namespace: infra-kong
  annotations:
    fluxcd.io/automated: "false"
    filter.fluxcd.io/chart-image: semver:~0.4
spec:
  releaseName: kong
  chart:
  **sourceRef:
    kind: GitRepository
    name: flux-system**
  install:
    createNamespace: true
  interval: 10m0s
  values:
    cassandra:
      image: cassandra
      tag: 3.11.2
      imagePullPolicy: IfNotPresent

$ cat kustomization.yaml
$  cat kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
**- kong.yaml**

i cant get flux to deploy this helmrelease 
$ flux get all
NAME                            READY   MESSAGE                         REVISION        SUSPENDED
gitrepository/flux-system       True    Fetched revision: prod/2f99aa1  prod/2f99aa1    False

NAME                            READY   MESSAGE                                                                                                                                  REVISION                                        SUSPENDED
**kustomization/flux-system       False   HelmRelease/infra-kong/kong dry-run failed, error: failed to create typed patch object: .spec.install: field not declared in schema      prod/14e807bf5969fcafbbccdb02a9683e6f2817b72c   False**

any idea how to get the helmreleases deployed. 
Any help would be greatly appreciated.

Thanks,
Venu

i added

**Comment by hiddeco** [comment]
Your `apiVersion` refers to the API version of the helm-operator, and should be changed to `helm.toolkit.fluxcd.io/v2beta1` for the helm-controller. See also this sample: https://github.com/fluxcd/helm-controller/blob/main/config/samples/helm_v2beta1_helmrelease_gitrepository.yaml#L1-L4

**Comment by 95438** [comment]
@hiddeco , thanks for the quick response and thanks for pointing out the apiversion.

Can you please let me know what the correct way is to layout the repo with all my deployments being helmcharts and i'm using a single repo for the flux-system components and my helmreleases which are sourced from the same git repo.

Here's how my git repo is laid out:
app-mkt-infra/clusters/prod/flux-system ( this is what flux components are )

**Infrastructure components**
app-mkt-infra/infrastructure/kong 
app-mkt-infra/infrastructure/cert-manager 

Deployment manifests (helmcharts)
app-mkt-infra/apps/mrkt-ui
app-mkt-infra/apps/mrkt-resource-api 
app-mkt-infra/apps/mrkt-product-api

As i understand the way it, all i need to do, is create helmrelease for each of the components above(in infra and apps ) and make sure i use the sourceRef as the same GitRepository which was used to bootstrap the cluster? is that correct?

Also, when do i use/create a kustomization if i have all my apps already in helmreleaseses?

Any clarification would be greatly appreciated....

Thanks,
Venu

**Comment by 95438** [comment]
@kingdonb , @hiddeco , i got the helmrelease to atleast try to get initialized by flux, but its showing its not ready state. 
can you please assist. 

$ flux get helmrelease -n infra-kong
NAME    READY   MESSAGE                                                 REVISION        SUSPENDED
**kong**    False   HelmChart **'infra-kong/infra-kong-kong'** is not ready                     False

I created a helmrelase named **"kong"**  to be created in namespace **"infra-kong**", the manifests are in  helmchart called **"kong"** in the repo path ./infrastructure/kong, but not sure why the helmrelease is being created as **infra-kong/infra-kong??** 

here's my kong-release.yaml in clusters/production/ folder :
 ---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: **HelmRelease**
metadata:
  name: **kong**
  namespace: **infra-kong**
spec:
  chart:
    spec:
      **chart: ./infrastructure/kong**
      **sourceRef:
        kind: GitRepository
        name: flux-system**
  install:
    createNamespace: true
  interval: 10m0s
  **targetNamespace: infra-kong**

Any ideas what am i missing?

**Comment by 95438** [comment]
Any help would be appreciated please...
why is flux/helm-controller trying to create a helmchart from the same path i defined(./infrastructure/kong) 
when i have a helmrelease defined with the same path? (./infrastructure/kong)?

really stuck here...any assistance/direction would really be appreciated....
please see the helmrelease manifest file below.
$ flux get all -A
NAMESPACE       NAME                            READY   MESSAGE                         REVISION        SUSPENDED
flux-system     gitrepository/flux-system       True    Fetched revision: prod/0c8f2a1  prod/0c8f2a1    False
infra-kong      gitrepository/app-mkt-infra     True    Fetched revision: prod/0c8f2a1  prod/0c8f2a1    False

NAMESPACE       NAME                            READY   MESSAGE                                         REVISION        SUSPENDED
infra-kong      **helmchart/infra-kong-kong**       True    Packaged 'kong' chart with version '0.1.0'.     0.1.0           False

NAMESPACE       NAME                    READY   MESSAGE                         REVISION        SUSPENDED
infra-kong      **helmrelease/kong**        False   **install retries exhausted**                       False

NAMESPACE       NAME                            READY   MESSAGE                         REVISION        SUSPENDED
flux-system     kustomization/flux-system       True    Applied revision: prod/0c8f2a1  prod/0c8f2a1    False

 MINGW64 ~/app-mkt-infra/clusters/production (prod)
**$ cat kong-release.yaml
---**
apiVersion: v1
kind: Namespace
metadata:
  name: infra-kong
---
apiVersion: v1
kind: Secret
metadata:
  name: app-mkt-infra-creds
  namespace: infra-kong
data:
  identity:  <base64 encoded private key>
  identity.pub:  <base64 encoded public key>
  known_hosts:  <base64 encoded known_hosts>
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: app-mkt-infra
  namespace: infra-kong
spec:
  interval: 5m0s
  url: ssh://git@github.com/xxxxxx/app-mkt-infra
  ref:
    branch: prod
  secretRef:
    name: app-mkt-infra-creds
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kong
  namespace: infra-kong
  annotations:
    app.kubernetes.io/managed-by: Helm
spec:
  chart:
    spec:
      chart: ./infrastructure/kong
      sourceRef:
        kind: GitRepository
        name: app-mkt-infra
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  interval: 5m0s

**Comment by kingdonb** [comment]
@95438 It looks like you needed to find this document:

https://fluxcd.io/docs/components/helm/helmreleases/#helm-release-placement

The `releaseName` flag has a default setting, which includes the namespace and the chart name. You can set it to something else.

**Comment by 95438** [comment]
@kingdonb , Thanks for the pointer. I got past this issue. I have a few more hurdles to cross...
I'm still trying to find my way through with using flux v2. 
I have a few questions. Would truly appreciate it if you can answer these for me. 
1) I'm using a single repo as the config repo as well as to host the  helmcharts/helmreleases for my application.
   when i bootstrapped this repo, flux created a GitRepository resource in the flux-system namespace. 
 -  for my helmreleases/charts that exist in their own namespaces, do i neeed to create GitRepository resource in each namespace referring to the single repo ( config repo as well as the helmcharts for my application)?
 -  i have 4 helmreleases that need to be deployed in a single namespace. 
 - do i create 1 namespace resource and 1 gitrepository resource in each namespace? 
 - if yes, how do i refer to this namespace resource and girepository resource in the 2nd/3rd and 4th helmreleases? 
 - can i use dependsOn to make helmrelease2 dependent on helmlrelease1 inside the same namespace?
 
appreciate it if you can answer my questions.

Thanks,
Venu
 -

**Comment by kingdonb** [comment]
Please join us in a different venue, as I've explained our [support policy](https://fluxcd.io/support/) demarcates which type of request is appropriate for which venue, an issue report is "Something is not working as intended / I found a bug"

This would be an appropriate question for the [Q&A](https://github.com/fluxcd/flux2/discussions/categories/q-a) section of FluxCD discussions board, or in the [#flux channel](https://cloud-native.slack.com/archives/CLAJ40HV3) on [CNCF Slack](https://slack.cncf.io/)
