### ISSUE TITLE
HelmRelease failing to download artifact that is successfully generated by source controller

### ISSUE THREAD

**Issue by tpabby1999** [fluxcd/helm-controller#433]
I am trying to deploy a HelmRelease using a HelmRepository as the source for the HelmChart. The Helm chart is pulled successfully:
NAME                                 CHART            VERSION   SOURCE KIND      SOURCE NAME      READY   STATUS                                                AGE
flux-system-metrics-server-release   metrics-server   3.8.2     HelmRepository   metrics-server   True    Pulled 'metrics-server' chart with version '3.8.2'.   24h

But the HelmRelease is giving this error:
Events:
  Type    Reason  Age                   From             Message
  ----    ------  ----                  ----             -------
  Normal  error   6m20s (x45 over 18h)  helm-controller  failed to download artifact, error: GET http://source-controller.flux-system.svc.cluster.local./helmchart/flux-system/flux-system-metrics-server-release/metrics-server-3.8.2.tgz giving up after 10 attempt(s): Get "http://source-controller.flux-system.svc.cluster.local./helmchart/flux-system/flux-system-metrics-server-release/metrics-server-3.8.2.tgz": dial tcp 172.20.55.99:80: i/o timeout

This same HelmRelease worked on this cluster previously but is not working currently (after uninstalling and re-installing flux2). Please let me know if there is more information I can provide to resolve this issue.

Thanks so much!

**Comment by hiddeco** [comment]
Any change a wrongly configured Network Policy is blocking access to the cluster, or you previously had to setup a custom cluster domain because e.g. the FQDN (`.cluster.local.`) could not be resolved?
