### ISSUE TITLE
Wrong `apiVersion` used in API docs

### ISSUE THREAD

**Issue by jonlao-khoros** [fluxcd/helm-controller#478]
In the [Helm Releases](https://fluxcd.io/docs/components/helm/helmreleases/) doc, there are two different `apiVersion` usages, is this intentional?

e.g.:
`helm.fluxcd.io/v2beta1`
`helm.toolkit.fluxcd.io/v2beta1`

**Comment by stefanprodan** [comment]
`helm.toolkit.fluxcd.io/v2beta1` should be used everywhere, we need to fix this in https://github.com/fluxcd/helm-controller/blob/main/docs/spec/v2beta1/helmreleases.md
