### ISSUE TITLE
PostRender 'Patches' Not Supported

### ISSUE THREAD

**Issue by coultenholt** [fluxcd/helm-controller#500]
## Description
As part of https://github.com/fluxcd/helm-controller/issues/104, helm `postRenders` were added as support. But it appears only [patchesStrategicMerge](https://kubectl.docs.kubernetes.io/references/kustomize/patchesstrategicmerge/), [patchesJson6902](https://kubectl.docs.kubernetes.io/references/kustomize/patchesjson6902/) and [images](https://kubectl.docs.kubernetes.io/references/kustomize/images/) were added in the PR https://github.com/fluxcd/helm-controller/pull/202. It seems to be missing [patches](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/). Though both the api-reference and the docs claim that its supported.

Api-Reference: https://fluxcd.io/docs/components/helm/api/#helm.toolkit.fluxcd.io/v2beta1.Kustomize
Docs: https://fluxcd.io/docs/components/helm/helmreleases/#post-renderers

**Comment by stefanprodan** [comment]
This was implemented in https://github.com/fluxcd/helm-controller/pull/432, upgrade Flux to latest and it should update the CRD.
