### ISSUE TITLE
Unable to depend on crossnamespace helmrelease when watch-all-namespaces=false

### ISSUE THREAD

**Issue by stgrace** [fluxcd/helm-controller#523]
When creating a dependency for a helmrelease in a different namespace, the controller throws an error that it cannot find a helmrelease in a different namespace when `--watch-all-namespaces=false`.

I feel like the watch-all-namespaces flag should only be used for reconciliation, not for dependencies. In our case the helm-controller is given enough rights to check for the status of another helmrelease in another namespace but is blocked by this watch-all-namespaces flag.
It's also not possible to remove this flag, since this is the only way to horizontally scale the helm-controllers in our cluster. One helm-controller for most of our clusters would not be able to reconcile everything properly.

**Comment by stefanprodan** [comment]
> One helm-controller for most of our clusters would not be able to reconcile everything properly.

Have you tried setting `--concurrent=100`, this should make helm-controller perform 100 installs/upgrades in parallel. Docs here: https://fluxcd.io/flux/cheatsheets/bootstrap/#increase-the-number-of-workers

**Comment by kvandenhoute** [comment]
Hi @stefanprodan ,

I'm in a similar situation, and I tried your suggestion. But what resources do you suggest? The docs show 2Gi for 100 concurrent, but that seems to be not even close to sufficient.

The following causes the helm-controller to go OOMKilled, I think 6Gi is already a stretch.
```    
Args:
      --events-addr=http://notification-controller/
      --concurrent=100
      --watch-all-namespaces=true
      --events-addr=http://notification-controller/
      --log-level=info
      --log-encoding=json
      --enable-leader-election
Limits:
      cpu:     2
      memory:  6Gi
Requests:
      cpu:      1
      memory:   2Gi
```

There are about 1000 helmreleases in my cluster with interval at 5min, installs take about 20 seconds. It doesn't crash immediately, only after 20-30min, sometimes even longer (probably depending on what is being installed.)

**Comment by stefanprodan** [comment]
You can now use sharding to scale helm-controller https://fluxcd.io/flux/installation/configuration/sharding/
