### ISSUE TITLE
Helm Upgrade fails, after PodSecurityPolicy was deprecated in K8s 1.25

### ISSUE THREAD

**Issue by wiswesser** [fluxcd/helm-controller#588]
This issue is similiar to #530 
After upgrading our cluster to 1.25 our grafana HelmRelease fails to upgrade to the newest version.The error we get is:
`Helm upgrade failed: unable to build kubernetes objects from current
        release manifest: resource mapping not found for name: "grafana"
        namespace: "" from "": no matches for kind "PodSecurityPolicy" in
        version "policy/v1beta1"`
This makes sense, since PodSecurityPolicy was removed in 1.25.

But as far as I can tell, grafana does not try to add PodSecurityPolicies if the cluster does not support them (See line 1 [here](https://github.com/grafana/helm-charts/blob/35436a5ca2153f11baedb0a613e2ec3a88f514d0/charts/grafana/templates/podsecuritypolicy.yaml)).
 I also changed the chart values to disable the resources in question manually, but this also did not help.

I suspect the Controller checks the files before even running the helm part? And because it sees Resourcekinds it doesn't know, stops and returns an error? Or something along those lines.

Is there maybe an Option to get a more detailed output from the Controller, to figure out what exactly is stopping it from continuing? I tried setting the log level to debug, but that didn't provide any usefull new output.

**Comment by wiswesser** [comment]
I have found the culprit (https://github.com/helm/helm/issues/7219). Now I just need to figure out how to work around this, but it seems to not be a Flux Problem.

**Comment by 0xdnL** [comment]
@wiswesser did you figure out how to work around this ?

**Comment by matheuscscp** [comment]
@0xdnL You can add a kustomize **inline** patch through the HelmRelease .spec.postRenderers field to remove the PodSecurityPolicy object:

* https://fluxcd.io/flux/components/helm/helmreleases/#post-renderers
* https://fabianlee.org/2023/04/20/kubernetes-using-a-delete-patch-with-kustomize/

**Comment by 0xdnL** [comment]
thanks @matheuscscp 🤝 

---

for future me and anyone else finding this, I solved it by using helm-mapkubeapis

from https://github.com/helm/helm/issues/11120#issuecomment-2022607838


```sh
helm plugin install https://github.com/helm/helm-mapkubeapis

helm list.   # get list of helm deployments

helm mapkubeapis DEPLOYMENT_NAME   # Upgrade each deployment by running
```

**Comment by matheuscscp** [comment]
Oh, got it, the issue was with an object reference already inside the release, in-cluster.
