### ISSUE TITLE
Missing image manifest 

### ISSUE THREAD

**Issue by dagb** [fluxcd/helm-controller#600]
Latest image seems to be missing manifest. 
sha256-138adba92408  dfddc826cf8271902eba7da8360ec3fc08e525d89d24d242d9ed.sig missing in repository [ghcr.io/fluxcd/helm-controller](http://ghcr.io/fluxcd/helm-controller)

This is observed in a flux instance that tries to retrieve the image.

**Comment by stefanprodan** [comment]
The `sig` layer is the Cosign signature, why would you use that as a container image?

**Comment by stefanprodan** [comment]
These are the images shipped with latest Flux:

```console
$ flux install --export | grep ghcr
        image: ghcr.io/fluxcd/helm-controller:v0.29.0
        image: ghcr.io/fluxcd/kustomize-controller:v0.33.0
        image: ghcr.io/fluxcd/notification-controller:v0.31.0
        image: ghcr.io/fluxcd/source-controller:v0.34.0
```

**Comment by dagb** [comment]
I just noticed that there was 0 downloads on the imagetag that flux is having an issue with. https://github.com/fluxcd/helm-controller/pkgs/container/helm-controller

But using the release tag is better anyway I think, but should it be possible to refer the sha-tag?

**Comment by stefanprodan** [comment]
The `sig` layer is a signature, has nothing to do with the actual image. If you want to use the SHA, GH displays it here https://github.com/fluxcd/helm-controller/pkgs/container/helm-controller/67446687?tag=v0.29.0

**Comment by stefanprodan** [comment]
Anyway I see no reason why would you use a SHA, we don't overrite tags, we follow semver, so it's best to use the tag.

**Comment by dagb** [comment]
Ok, could be some misconfiguration the flux instance. Sorry for reporting this as an issue.

**Comment by dagb** [comment]
I did some testing with

docker manifest inspect --verbose ghcr.io/fluxcd/helm-controller:v0.28.1
which returns a manifest.

but this does not
docker manifest inspect --verbose ghcr.io/fluxcd/helm-controller:v0.29
manifest unknown

**Comment by stefanprodan** [comment]
Well that's a Docker bug, works fine with crane:

```console
$ crane manifest ghcr.io/fluxcd/helm-controller:v0.29.0
{
  "mediaType": "application/vnd.oci.image.index.v1+json",
  "schemaVersion": 2,
  "manifests": [
    {
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "digest": "sha256:c37ddefc9aa52dd4193eb3ec970f679edb89f030efde19b61f6dc55ef5ab646e",
      "size": 865,
      "platform": {
        "architecture": "amd64",
        "os": "linux"
      }
    },
    {
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "digest": "sha256:9a8b1ff0773d46534451996b36ea87ba515511672be176ac491828d769caf700",
      "size": 865,
      "platform": {
        "architecture": "arm",
        "os": "linux",
        "variant": "v7"
      }
    },
    {
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "digest": "sha256:83550c8b00c50e7b940db12ea80bc3fe45b0b4d6b61b0acd0e9d34ba365ad619",
      "size": 865,
      "platform": {
        "architecture": "arm64",
        "os": "linux"
      }
    },
    {
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "digest": "sha256:9a28867faa0547576ac110fe1306d9547aec700873d2985ef1192ccb3135634a",
      "size": 840,
      "annotations": {
        "vnd.docker.reference.digest": "sha256:c37ddefc9aa52dd4193eb3ec970f679edb89f030efde19b61f6dc55ef5ab646e",
        "vnd.docker.reference.type": "attestation-manifest"
      },
      "platform": {
        "architecture": "unknown",
        "os": "unknown"
      }
    },
    {
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "digest": "sha256:6ad871a8283ef3212b9d3e53531188529422df5912fb01a739562557339cc672",
      "size": 840,
      "annotations": {
        "vnd.docker.reference.digest": "sha256:9a8b1ff0773d46534451996b36ea87ba515511672be176ac491828d769caf700",
        "vnd.docker.reference.type": "attestation-manifest"
      },
      "platform": {
        "architecture": "unknown",
        "os": "unknown"
      }
    },
    {
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "digest": "sha256:00e71909ad39165ed34d8c9770286b87a547d2a1f032266ba336a39a40beac60",
      "size": 840,
      "annotations": {
        "vnd.docker.reference.digest": "sha256:83550c8b00c50e7b940db12ea80bc3fe45b0b4d6b61b0acd0e9d34ba365ad619",
        "vnd.docker.reference.type": "attestation-manifest"
      },
      "platform": {
        "architecture": "unknown",
        "os": "unknown"
      }
    }
  ]
}
```

You need to also use buildx like so:

```
docker buildx imagetools inspect ghcr.io/fluxcd/helm-controller:v0.29.0
```

**Comment by stefanprodan** [comment]
@dagb we build the images with Docker Buildkit, and in the latest release, Docker switch the images to `application/vnd.oci.image.index.v1+json`, older versions were using `application/vnd.docker.distribution.manifest.list.v2+json`. I guess `docker manifest` wasn't update along with Buildkit... you may want to report this bug to the Docker team.

**Comment by dagb** [comment]
Thanks for noticing me. In fact docker manifest inspect now works, but flux still complains. Guess there is a bug there too.

```
flux will fail to auto-release workloads with matching images, ask the repository administrator to fix the inconsistency","ts":"2023-02-06T06:53:31.943522145Z","warn":"manifest for tag sha256-138adba92408dfddc826cf8271902eba7da8360ec3fc08e525d89d24d242d9ed.sig missing in repository ghcr.io/fluxcd/helm-controller
```

**Comment by stefanprodan** [comment]
Who longs that error? I f it’s Flux v1, we no longer maintain it.

**Comment by dagb** [comment]
Yes it is flux v1, so that could be the problem here.

**Comment by stefanprodan** [comment]
Flux v1 doesn't work on signed images, you need use Flux v2 image automation.
