### ISSUE TITLE
OCIRepository Missing from CRD

### ISSUE THREAD

**Issue by estein9825** [fluxcd/helm-controller#602]
Helm supports OCIRepository (https://helm.sh/docs/topics/registries/) but the HelmRelease CRD doesn't offer it as an option. https://github.com/fluxcd/helm-controller/blob/main/config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml#L77

This is what I get from the flux logs

```
{"level":"error","ts":"2023-02-03T21:19:26.330Z","logger":"controller.kustomization","msg":"Reconciliation failed after 2.786559973s, next try in 5m0s","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"XXXX","namespace":"flux-system","revision":"main/XXXXXX","error":"HelmRelease/xxx/xxx dry-run failed, reason: Invalid, error: HelmRelease.helm.toolkit.fluxcd.io \"xxx\" is invalid: spec.chart.spec.sourceRef.kind: Unsupported value: \"OCIRepository\": supported values: \"HelmRepository\", \"GitRepository\", \"Bucket\"\n"}
```

When will the CRD be updated to support OCIRepository?

**Comment by somtochiama** [comment]
You can specify `spec.type` as `oci` in a `HelmRepository`.
Please take a look at the docs https://fluxcd.io/flux/guides/helmreleases/#helm-oci-repository

**Comment by stefanprodan** [comment]
`OCIRepository` is an API made for [OCI artifacts produced by the Flux CLI](https://fluxcd.io/flux/cheatsheets/oci-artifacts/), for OCI artifacts produced with the Helm CLI, you can use the `HelmRepository` API as [showed here](https://fluxcd.io/flux/cheatsheets/oci-artifacts/#helm-oci).

**Comment by estein9825** [comment]
Yes, after I updated to the newest flux operator, the OCI installed through the helmrepository option just fine.
