### ISSUE TITLE
[Question] Helm upgrade option for Atomic

### ISSUE THREAD

**Issue by jpae** [fluxcd/helm-controller#615]
Looking at helm-operator there was a possible [Atomic option](https://github.com/fluxcd/helm-operator/blob/4dc90d7766bc7a10961c6dc3b2ea6e4d2282c6e8/pkg/helm/options.go#L41). Is the Atomic option configurable in helm-controller?

**Comment by kingdonb** [comment]
Helm Operator has the `atomic` option, which is not quite related to the roadmap entry for Helm Controller:

* https://fluxcd.io/roadmap/#flux-helm-ga-q2-2023 ("Atomic Reconciliation of Helmreleases")

There are a few different things that people mean when they say atomic, with respect to Helm. That flag from Helm Operator `atomic` was replaced in Flux v2, with a more broadly scoped configuration:

https://fluxcd.io/flux/components/helm/helmreleases/#configuring-failure-remediation

Can you say a bit more about what you were hoping to get from the Atomic option? Is it just a drop-in replacement for the old behavior that you're looking for?

`remediateLastFailure: false` - will leave the failed resources in place (so you can debug what went wrong) whereas

`remediateLastFailure: true` - will actually roll back the failure when the number of retries you have configured is exhausted. That's similar to `atomic` from HelmRelease in Helm Operator. So, in brief, the "atomic" mode has been replaced by "failure remediation" settings in Helm Controller.

Hope that is what you were looking for!

The "atomic" stuff that's discussed in the roadmap is all about whether or not Helm Controller can perform drift detection and reliably revert changes to your Helm release's manifests (output) when someone makes a change inside the cluster. That's a different thing, was never supported in Helm Operator before, but if that's what you are looking for, I hear it might be landing soon (at least in an experimental form!)

* https://github.com/fluxcd/helm-controller/pull/617

**Comment by hiddeco** [comment]
Closing this, as I think @kingdonb has answered your question accordingly. The changes Kingdon is further talking about have landed in the `v0.37.0` release of the helm-controller, and you can read more about it in [this blog post](https://fluxcd.io/blog/2023/12/flux-v2.2.0/).
