### ISSUE TITLE
Can't control the DNS flag when rendering

### ISSUE THREAD

**Issue by geNAZt** [fluxcd/helm-controller#618]
With introducing https://github.com/helm/helm/commit/863bc74e5ad090b97f69dcb643be8d969b07e7cf helm disabled DNS resolving by default. We have charts which depend on this functionality. This is not a problem with the client since we can enable it with a flag.

The helm-controller currently doesn't set this on its install configuration. It would be awesome if we can control this feature from the outside :)

Thanks

**Comment by hiddeco** [comment]
We can not enable this by default as this would leave the controller vulnerable to the same attack vector in a multi-tenant setup, but we can put it behind a feature flag. Will ensure this gets added soon.
