### ISSUE TITLE
HelmController crashes on multiple large deployments in single configuration

### ISSUE THREAD

**Issue by bavneetsingh16** [fluxcd/helm-controller#646]
Helm controller crashes when there are multiple deployments(>10) in a single configuration and each of the deployments create a container which uses an image of size ~4GB. Can someone please confirm if there is a limitation for flux helm controller to handle a request this large? And if so, what would be the ideal way to deploy large amounts of containers on a single-node cluster?

**Comment by kingdonb** [comment]
It sounds like your node is running out of memory, is Helm Controller crashing or is it being OOM killed? It might not be obvious which, but if you're having trouble tracking down error logs, then the likely culprit is an OOM Killer.

Please provide more information about the version of Flux that is in use, the output of `flux check` will tell everything here. There have been recent and major changes in this neighborhood in the code that will affect memory usage (it should go down) and will give more control over when and how the Helm Controller dies in scenarios like this.

https://github.com/fluxcd/flux2/releases/tag/v0.41.0 - notes about it can be found here.

So, the latest MINOR release of Flux has some changes that target Out-of-Memory issues, such that you can tell Helm Controller to shut down gracefully when it's running out of memory. However in that case the core issue is still running out of memory.

If the situation is that Helm Controller is being run out of town by other pods that take up all available memory, that's external pressure and Helm Controller is definitely going to have problems if it cannot access as much memory as it needs.

This is quite speculative based on limited information in your report. We will need to know more to help further.

In the latest flux CLI, we can gather some statistics directly from Flux by running `flux stats -A` – these stats don't include any details about memory usage, (maybe this is something to consider adding for the future) – it only gives ephemeral storage numbers for now, which are useful for telling users about which git repositories are blowing out the cluster, (but not so much useful for HelmReleases that are likely bowing to memory pressure as described above. Why I think we might want to consider adding more details here...)

I can add more information here about how to determine the right amount of memory to reserve for Helm Controller, if that will help. Meanwhile, please provide more information – the output of `flux check` and whether you have currently made any adjustment to the memory limits and requests. Prometheus monitoring or the metrics API will help narrow down the details about the memory usage questions.
