### ISSUE TITLE
`Helm upgrade succeeded` event throttled even though `.spec.values` has changed

### ISSUE THREAD

**Issue by aristapimenta** [fluxcd/helm-controller#678]
Hi, I followed this super-cool guide: https://fluxcd.io/flux/use-cases/gh-actions-helm-promotion/

The idea is amazing, but right now we have an event delivery reliability problem, meaning that sometimes helm-controller will successfully execute a Helm upgrade but this event will not be delivered to notification-controller and therefore also not delivered to GitHub Actions.

Basically, I observed this by changing a field under `.spec.values` of my `HelmRelease` and letting my `apps` parent `Kustomization` reconcile the `HelmRelease` manifest. I did this many times over. Every time I saw a successful Helm upgrade as expected, and I could also always immediately observe the changed `HelmRelease` object spec via `watch kubectl get hr -o yaml ...`. I was also watching `kubectl describe hr | grep succeeded` and observed the line:

```
  Normal  info    7m4s (x6 over 13m)   helm-controller  Helm upgrade succeeded
```

Every single time I changed something under `.spec.values`, I saw both the `x6` counter increase by one and the changed `HelmRelease` spec, immediately.

At the same time, I was also watching the `grep Dispatching` logs from notification-controller, and consistently only the first event was delivered to GitHub Actions. That's when I realized that the k8s event recorder is probably throttling the delivery of this event to notification-controller.

Fixing this behavior would be extremely crucial for me to successfully introduce Flux at my job, as the release promotion across clusters workflow is super important for us.

I'd be more than happy to contribute with this fix.

**Comment by matheuscscp** [comment]
Actually after reading the code it doesn't look like event recorder is the one holding the events back, but actually the notification-controller server itself. Gonna try to get to the bottom of this again and update here.

**Comment by matheuscscp** [comment]
Okay I see that the notification-controller even has a CLI arg to specify the rate limiting interval whose default is 5min. Could anybody provide guidance on what to do in this case? Is it unsafe to disable this rate limiting? Does it just depend entirely on my use cases? I'd definitely disable this rate limiting to solve my Helm promotion problem here if there were no bad consequences. Appreciate any guidance!

**Comment by aristapimenta** [comment]
Looking at how notification-controller calculates the event key for rate limiting:

https://github.com/fluxcd/notification-controller/blob/18c49ad361253bb8ffe0c14fa068a10e04b6d81d/internal/server/event_server.go#L151-L152

```go
	comps := []string{"event", event.InvolvedObject.Name, event.InvolvedObject.Namespace, event.InvolvedObject.Kind, event.Message}
	revString, ok := event.Metadata[eventv1.MetaRevisionKey]
```

I thought about adding a metadata field in the Helm events with a stable hash of the `spec.values` field. Looks like the best solution to me (my upgrade events are being rate-limited because the artifact revision doesn't change, only the values).

Furthermore, why not include all the metadata fields in this rate limiting logic?

**Comment by aristapimenta** [comment]
By the way, I found out that at least in the case of events sent by the helm-controller the revision is not being considered in the rate limiting above.

Here is my proof:

```json
{
    "level": "debug",
    "ts": "2023-04-30T19:56:25.319Z",
    "logger": "event-server",
    "msg": "Discarding event, rate limiting duplicate events",
    "reconciler kind": "HelmRelease",
    "name": "toolkit",
    "namespace": "toolkit",
    "event metadata": {
        "helm.toolkit.fluxcd.io/revision": "0.1.5"
    },
    "rate limiting key": "event/toolkit/toolkit/HelmRelease/Helm upgrade succeeded"
}
```

Printed this debug log using this: https://github.com/fluxcd/notification-controller/pull/516

The event key function is retrieving `revision` while helm-controllers sends the event with `helm.toolkit.fluxcd.io/revision` instead.

**Comment by aristapimenta** [comment]
Here's a fix for the revision problem: https://github.com/fluxcd/notification-controller/pull/517
