### ISSUE TITLE
Feature request: Report culprit for timed-out HelmRelease.

### ISSUE THREAD

**Issue by MartinEmrich** [fluxcd/helm-controller#716]
After the latest release of one of our helm charts here, the HelmRelease times out with `client rate limiter Wait returned an error: context deadline exceeded`.

I am aware of the timeouts and that helm-controller tries to "wait" for everything to become "ready". But here, everything looks ok, nothing happens.
At first glance (see below), all Deployment Pods are running (1/1), including all Pod Readiness Gates. All services seem happy. All Deployments seem happy.

The helm-controller also only logs that single line:

````
{"level":"error","ts":"2023-06-29T08:04:56.337Z","msg":"Reconciler error","controller":"helmrelease","controllerGroup":"helm.toolkit.fluxcd.io","controllerKind":"HelmRelease","HelmRelease":{"name":"xxx","namespace":"yyy"},"namespace":"yyy","name":"xxx","reconcileID":"6c3cdb35-edf3-431c-81e8-1273212dee94","error":"Helm upgrade failed: context deadline exceeded"}
````

Only after staring at Logs, Kubernetes Events etc. for over an hour, I noticed a Deployment Pod not being able to be scheduled due to a missing service account....

Can the debug level be increased to include that information e.g. in the helm-controller log, or even in the "result line" printed when running "flux reconcile"?

That would be nice!

**Comment by somtochiama** [comment]
You can [customize flux](https://fluxcd.io/flux/cheatsheets/bootstrap/#how-to-customize-flux) so the change isn't reverted on the next reconcile

**Comment by MartinEmrich** [comment]
@somtochiama thanks, but that only applies if one uses Flux to flux itself. I/we prefer `flux install`, which (I just tried it) overwrites the helm-controller deployment. 

But that's good enough for now, I need it only for a short time in case of such a stubborn HelmRelease.

**Comment by stefanprodan** [comment]
You can set the log level with `flux install --log-level=debug`
