### ISSUE TITLE
HelmRepository issue: "remote error: tls: unrecognized name"

### ISSUE THREAD

**Issue by rzumbado** [fluxcd/helm-controller#752]
Let me start by saying I'm a total noob trying to setup my home-lab.

### Describe the bug
I am trying to deploy PostgrelSQL to my K8 cluster. I am using this helm chart: https://artifacthub.io/packages/helm/bitnami/postgresql
K8 cluster seems fine, FLUX is installed all checks passed.

But I get this error when flux tries to pull the helm repository:
`failed to fetch Helm repository index: failed to cache index to temporary file: Get "https://charts.bitnami.com/bitnami/index.yaml": remote error: tls: unrecognized name`

I have been googling for 2 days straight no luck.. been trying to understand kubectl logs and flux logs but can't find anything that shreds some light to the issue.

### Additional Info

`kubectl describe node k8-master`
![image](https://github.com/fluxcd/helm-controller/assets/20713805/fb047060-1fec-4595-bad7-26a87d41b700)
![image](https://github.com/fluxcd/helm-controller/assets/20713805/2d169980-672f-47d4-a081-35cb17983435)

`repository.yaml`
![image](https://github.com/fluxcd/helm-controller/assets/20713805/d2cf7b2f-9f25-4a38-a109-1fee05a880c6)

`chart-release.yaml`
![image](https://github.com/fluxcd/helm-controller/assets/20713805/3601b547-0fe7-4559-bc10-aa88838e379d)

`flux check --pre`
![image](https://github.com/fluxcd/helm-controller/assets/20713805/48827295-45f7-40bb-99c8-de2d5fd7b5ad)

`flux check`
![image](https://github.com/fluxcd/helm-controller/assets/20713805/6c559c25-e9df-42ef-9838-9d6c833ac310)

`flux logs --namespace=sic --level=error`
![image](https://github.com/fluxcd/helm-controller/assets/20713805/4605d124-ed27-452a-90b2-5ab71a0bb1d9)

`kubectl get helmrepositories.source.toolkit.fluxcd.io -A`
![image](https://github.com/fluxcd/helm-controller/assets/20713805/126019f2-63d0-463e-b6df-4823f2c9cd58)

**Comment by hiddeco** [comment]
Unable to reproduce on a freshly bootstrapped kind cluster:

```console
$ flux install                                                             
✚ generating manifests
✔ manifests build completed
► installing components in flux-system namespace
CustomResourceDefinition/alerts.notification.toolkit.fluxcd.io created
CustomResourceDefinition/buckets.source.toolkit.fluxcd.io created
CustomResourceDefinition/gitrepositories.source.toolkit.fluxcd.io created
CustomResourceDefinition/helmcharts.source.toolkit.fluxcd.io created
CustomResourceDefinition/helmreleases.helm.toolkit.fluxcd.io created
CustomResourceDefinition/helmrepositories.source.toolkit.fluxcd.io created
CustomResourceDefinition/kustomizations.kustomize.toolkit.fluxcd.io created
CustomResourceDefinition/ocirepositories.source.toolkit.fluxcd.io created
CustomResourceDefinition/providers.notification.toolkit.fluxcd.io created
CustomResourceDefinition/receivers.notification.toolkit.fluxcd.io created
Namespace/flux-system created
ResourceQuota/flux-system/critical-pods-flux-system created
ServiceAccount/flux-system/helm-controller created
ServiceAccount/flux-system/kustomize-controller created
ServiceAccount/flux-system/notification-controller created
ServiceAccount/flux-system/source-controller created
ClusterRole/crd-controller-flux-system created
ClusterRole/flux-edit-flux-system created
ClusterRole/flux-view-flux-system created
ClusterRoleBinding/cluster-reconciler-flux-system created
ClusterRoleBinding/crd-controller-flux-system created
Service/flux-system/notification-controller created
Service/flux-system/source-controller created
Service/flux-system/webhook-receiver created
Deployment/flux-system/helm-controller created
Deployment/flux-system/kustomize-controller created
Deployment/flux-system/notification-controller created
Deployment/flux-system/source-controller created
NetworkPolicy/flux-system/allow-egress created
NetworkPolicy/flux-system/allow-scraping created
NetworkPolicy/flux-system/allow-webhooks created
◎ verifying installation
✔ helm-controller: deployment ready
✔ kustomize-controller: deployment ready
✔ notification-controller: deployment ready
✔ source-controller: deployment ready
✔ install finished

$ flux check
► checking prerequisites
✔ Kubernetes 1.25.3 >=1.24.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.35.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v1.0.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v1.0.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v1.0.1
► checking crds
✔ alerts.notification.toolkit.fluxcd.io/v1beta2
✔ buckets.source.toolkit.fluxcd.io/v1beta2
✔ gitrepositories.source.toolkit.fluxcd.io/v1
✔ helmcharts.source.toolkit.fluxcd.io/v1beta2
✔ helmreleases.helm.toolkit.fluxcd.io/v2beta1
✔ helmrepositories.source.toolkit.fluxcd.io/v1beta2
✔ kustomizations.kustomize.toolkit.fluxcd.io/v1
✔ ocirepositories.source.toolkit.fluxcd.io/v1beta2
✔ providers.notification.toolkit.fluxcd.io/v1beta2
✔ receivers.notification.toolkit.fluxcd.io/v1
✔ all checks passed

$ flux create source helm bitnami --url https://charts.bitnami.com/bitnami/             
✚ generating HelmRepository source
► applying HelmRepository source
✔ source created
◎ waiting for HelmRepository source reconciliation
✔ HelmRepository source reconciliation completed
✔ fetched revision: sha256:6a7ff8f80f9b14e9f276676e7bdbbb6e4ebc4e33da22411a4cebbe113f54a6d1

$ flux create source helm bitnami-new --url https://repo.vmware.com/bitnami-files/
✚ generating HelmRepository source
► applying HelmRepository source
✔ source created
◎ waiting for HelmRepository source reconciliation
✔ HelmRepository source reconciliation completed
✔ fetched revision: sha256:6a7ff8f80f9b14e9f276676e7bdbbb6e4ebc4e33da22411a4cebbe113f54a6d1
```

Which makes me think this is related to the network configuration of your cluster.

One thing that did recently change is that `https://charts.bitnami.com/bitnami/` was moved to `https://repo.vmware.com/bitnami-files/`, which may be worth looking into.

**Comment by rzumbado** [comment]
It's really odd.. I can install the helm chart by doing 
`helm repo add bitnami https://charts.bitnami.com/bitnami`

and install them by running
`helm install psql bitnami/postgresql --version 12.8.2`

but using flux just doesn't work... 

running the `flux create source helm bitnami --url https://charts.bitnami.com/bitnami/` command will output the `failed to fetch Helm repository index: failed to cache index to temporary file: Get "https://charts.bitnami.com/bitnami/index.yaml": remote error: tls: unrecognized name` error...

This morning I spotted this error:
`
2023-08-11T12:13:42.295Z error HelmRepository/bitnami.flux-system - Reconciler error Patch "https://10.96.0.1:443/apis/source.toolkit.fluxcd.io/v1beta2/namespaces/flux-system/helmrepositories/bitnami/status?fieldManager=source-controller": dial tcp 10.96.0.1:443: connect: connection refused
`

I am currently digging trying to find the root cause...

**Comment by hiddeco** [comment]
`helm repo add` uses the network of your local machine, then `helm install` uses the data from your local machine to build Kubernetes resources and apply those to your remote cluster.

I suspect running `helm repo add` within a Pod in the cluster would yield the same (or a likewise) error.

**Comment by rzumbado** [comment]
Well.. you are correct.

If I spawn a test pod with `kubectl run test --rm --tty -i --restart='Never' --image  ubuntu --namespace default --command -- bash` and try to run `apt update` I get this:
![image](https://github.com/fluxcd/helm-controller/assets/20713805/6f61870f-58a3-491e-9a3d-9c7ef223897b)

I hide my IP address in that screenshot because it is showing my actual IP.. so all domains I try to reach are pointing to my public IP address.. WTF lol

Well, at least this is progress, I am now digging why the heck my pods are not reaching internet and why they get my public IP from whatever DNS they are using..

**Comment by rzumbado** [comment]
Finally I figure out the problem, thanks @hiddeco for your posts because that lead me to the issue in question.

Following this troubleshooting guide (https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/) I was able to realize that my DNS config was a bit off (my home lan network config) since the domain used for my lan was set to one of my real domains and that added this line to the resolve.conf file:

`search mydomain.com` (where mydomain.com was actually my real domain)

And so, the pods were appending that domain to name resolution like "google.com.mydomain.com", hence providing my public IP since that domain @ record points to it.

So yeah, it was my own stupidity but I was finally able to figure it out. All is working great with flux now. THANKS!!!
