### ISSUE TITLE
don't reconcile resources with owner references unless configured to do so

### ISSUE THREAD

**Issue by joejulian** [fluxcd/helm-controller#769]
If the flux controllers are used in downstream operators, those operators can (should) create the flux resources with owner references. If used in this way, by not reconciling resources with owner references by default, we can prevent controller contention over the flux resources.

**Comment by hiddeco** [comment]
This would not fit well with all use cases in which someone may take ownership of a resource. For example, another controller generating resources on behalf of a user based on templates while registering an owner reference to handle garbage collection (the right way).

Which is something we would like to support out of the box; without it creating configuration hurdles.
