### ISSUE TITLE
external-dns extraArgs failing to format template properly

### ISSUE THREAD

**Issue by cdenneen** [fluxcd/helm-controller#779]
Running latest flux 2.1.1

Having issue when deploying helmrelease of external-dns with the following values:

```
extraArgs:
- --aws-assume-role=role-arn
```

This should yield deployment with:

```
          args:
            - --log-level=info
            - --log-format=text
            - --interval=1m
            - --source=service
            - --source=ingress
            - --policy=upsert-only
            - --registry=txt
            - --provider=aws
            - --aws-assume-role=role-arn
```

Running locally with `helm template . -f test.yaml` it does.

When rendered via helm-controller it yields:

```
- --0=--aws-assume-role=role-arn
```

Looking at the helmrelease on the cluster the `values:` map looks fine and the correct format as provided to it, it's just the resulting deployment yaml that has this weird `--0=` addition to it.

**Comment by hiddeco** [comment]
What happens when you put it between quotes?

**Comment by cdenneen** [comment]
`- "--aws-assume-role=role-arn"` and `- --aws-assume-role="role-arn"` all yield the same thing.

**Comment by Sargastico** [comment]
did you find a solution @cdenneen ??

**Comment by Sargastico** [comment]
I found a way to declare `extraArgs` without causing this this weird `--0=` addition

- https://github.com/grafana/loki/issues/9143#issuecomment-1794798363
