### ISSUE TITLE
Helm charts continuously failing with " is not ready","controller":"helmrelease","controllerGroup":"helm.toolkit.fluxcd.io","controllerKind":"HelmRelease","HelmRelease":"  

### ISSUE THREAD

**Issue by varunthakur2480** [fluxcd/helm-controller#813]
We have started seeing this recently in our clusters 
The logs go into a long lop of  
 **is not ready","controller":"helmrelease","controllerGroup":"helm.toolkit.fluxcd.io","controllerKind":"HelmRelease","HelmRelease":**
errors 
and then recovers automatically.
we are on /helm-controller:v0.36.0
And it is important to mention that the charts have not changed for a while

**Comment by hiddeco** [comment]
Your source-controller Pod is likely restarted when this happens, causing the charts to be temporarily unavailable while it is working on refetching the charts.

**Comment by varunthakur2480** [comment]
Thanks for coming back
I have checked that the source controller pod is working fine and has not restarted for some time. It was restarted by me yesterday and the pod has been running for over 5 days otherwise 
![image](https://github.com/fluxcd/helm-controller/assets/9651171/b15d2813-43ef-4cc4-bd24-b709b2f07a84)

**Comment by somtochiama** [comment]
what do you see when you run `flux get source charts`

**Comment by varunthakur2480** [comment]
dev2-e2-dev-xxx       dxxxx                                    dxcloudcore                          >0.0.0-snapshot <=9.9.999-snapshot   HelmRepository   xxx-helm-snapshots          5d12h   False   invalid chart reference: failed to get chart version for remote reference: no chart name found

**Comment by somtochiama** [comment]
what does your helm release yaml look like? is your `chart.spec.chart` correct?

**Comment by varunthakur2480** [comment]
tl get helmreleases.helm.toolkit.fluxcd.io -n yyy2-e2-yyy-xxx-xxx-demo xxx -o yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  creationTimestamp: "2023-11-20T15:46:10Z"
  finalizers:
  - finalizers.fluxcd.io
  generation: 1
  labels:
    kustomize.toolkit.fluxcd.io/name: gke-iac
    kustomize.toolkit.fluxcd.io/namespace: yyy2-e2-yyy-xxx-xxx-demo
  name: xxx
  namespace: yyy2-e2-yyy-xxx-xxx-demo
  resourceVersion: "307955079"
  uid: fb6f1db8-f750-46d8-8fd3-0a3970a5d2e6
spec:
  chart:
    spec:
      chart: dxcloudcore
      reconcileStrategy: ChartVersion
      sourceRef:
        apiVersion: source.toolkit.fluxcd.io/v1beta1
        kind: HelmRepository
        name: xxx-helm-releases
      valuesFile: values.gke.demo.yaml
      version: '>0.1.0 <=1.0.999'
  install:
    crds: Skip
  interval: 1m0s
  timeout: 10h0m0s
  upgrade:
    crds: Skip
    disableWait: true

**Comment by hiddeco** [comment]
Can you `kubectl describe` the `HelmChart` which was created by the `HelmRelease`? I suspect this will tell you something is wrong with it.

**Comment by varunthakur2480** [comment]
any updates on this ? we have application teams chasing us constantly

**Comment by hiddeco** [comment]
The error indicates that the provided chart name is not (anymore) found in the Helm repository index. You should figure out why this is the case.

**Comment by varunthakur2480** [comment]
thanks but the point I wanted to make is : that it fails for some time and later works . Alternating manner remains broken for ~30 min and then recovers

**Comment by varunthakur2480** [comment]
it is set to poll the repo very minute 
spec:
  interval: 1m0s
  passCredentials: true
  provider: generic
  secretRef:
    name: flux-helm-secret
  timeout: 1m0s


Would that be a cause of concern ?

**Comment by hiddeco** [comment]
What I would do to debug this is to compare the index when it fails to the index when it succeeds. Instructions on how to fetch an Artifact from the source-controller can be found in https://github.com/fluxcd/source-controller/issues/1264#issuecomment-1805441206

**Comment by hiddeco** [comment]
In any case: I do not suspect this to be an actual issue with the source-controller and/or helm-controller, but rather an issue with the Helm repository index which is being produced.

**Comment by varunthakur2480** [comment]
thanks for all the support with this. It turns out that we switched to folder paths in artifactory Helm repos few days ago 
https://artifactoryur/xxx/helm-re/folder
And it looks like Jfrog Artifactory has a bug somewhere which returns empty list when helm tries to query it. 
Moving back to charts at root of the repo fixed the issue.
I will raise a bug with Jfrog.
This issue can be closed.

**Comment by varunthakur2480** [comment]
issue identified with Repository hosting solution Jfrog Artifactory
