### ISSUE TITLE
helmrelase Unable to perceive changes in resources

### ISSUE THREAD

**Issue by shencan** [fluxcd/helm-controller#847]
I create a helm chart containing a nginx deployment and manage it with helmrelase, and when the nginx deployment is complete (helmrelase status is 
Release reconciliation succeeded). If I manually modify the nginx deployment configuration and trigger helmrelase reconcile manually, the deployment configuration will not be overwritten

**Comment by hiddeco** [comment]
Please see #643, which contains all the information you are looking for.
