### ISSUE TITLE
set-file usage

### ISSUE THREAD

**Issue by runningman84** [fluxcd/helm-controller#868]
In a typical helm install you can do thing like this:
`````
$ helm install --set-file my_script=dothings.sh myredis ./redis
`````
how is this possible with the helm-controller?

**Comment by stefanprodan** [comment]
With `valuesFrom` see https://fluxcd.io/flux/components/helm/helmreleases/#values

**Comment by st-akorotkov** [comment]
@stefanprodan This isn't `--set-file` parity only `--set` which has it's own limitation in terms of content (almost everything should be escaped)
