### ISSUE TITLE
Upgrde Helm to 3.14.0 or later (fixes issue in treatment of parent/child chart treatment)

### ISSUE THREAD

**Issue by joaocc** [fluxcd/helm-controller#878]
Hi,
After a lot of pain trying to identify why a non-trivial chart with subcharts was resulting in strange values, we found out this issue https://github.com/helm/helm/pull/12480 and https://github.com/helm/helm/issues/12460.
It seems that helm 3.13 changed the priority of parent/child values, which was then fixed in helm 3.14.0.
We would kindly ask if this could be included in an emergency release of the controller (and then propagated to flux or get some indications how it can be deployed)?
We believe this fix is critical, to fix the regression caused by 3.13.
Thanks

**Comment by stefanprodan** [comment]
Helm 3.14.0 comes with Kubernetes 1.29 while Flux controller runtime is on Kubernetes 1.28, we need to migrate all controllers to 1.28 APIs and client-go before we can make a release with this. At best we can try create a RC build for helm-controller after we release Flux v2.2.3 this week https://github.com/fluxcd/flux2/issues/4556

**Comment by stefanprodan** [comment]
@joaocc you can use the controller image posted here to switch to Helm 3.14 https://github.com/fluxcd/helm-controller/pull/879

**Comment by joaocc** [comment]
Thanks for the suggestion. We will take a look to the technique, and try to adopt to our deployment strategy (helm + custom bootstrapping from terraform), and point image tag to `preview-0d77acf1`.
Thanks for the prompt response.

**Comment by joaocc** [comment]
Hi.  The workaround worked very well (sorry for not having provided feedback sooner). Thanks!
Shall we point the image to `v0.37.4-helm3140` (as per https://github.com/fluxcd/helm-controller/pull/879) or it's better to wait for next full flux2 release?
Thanks
