### ISSUE TITLE
HelmRelease verify provider gpg

### ISSUE THREAD

**Issue by wrenix** [fluxcd/helm-controller#892]
I like to verify chart with gpg:
https://helm.sh/docs/topics/provenance/

like the chart-releaser creates:
https://github.com/helm/chart-releaser/blob/main/doc/cr_package.md

PS: cosign is nice but not the default way in helm ...

**Comment by stefanprodan** [comment]
We have no plans on supporting GPG, soon you'll be able to chose between Cosign and Notation.
