### ISSUE TITLE
Only deploy prerelease versions

### ISSUE THREAD

**Issue by PeteMac88** [fluxcd/helm-controller#903]
Hey there,
we have a use case for which we automatically want to deploy prerelease versions of a chart but skip the release versions. In our case the semver tag has following format "x.x.x-staging.x". So for example:

1.0.0-staging.1 -> deploy
1.0.0-staging.2 -> deploy
1.0.0 -> skip
1.0.1-staging.1 -> deploy

When we use a version declaration like `version: ">1.0.0-0"` also the release version is deployed.

Is this possible? I know this is not really the way you work with semver versioning and we have the possibility to release a second chart but if its possible we could skip this additional effort.

thanks

**Comment by stefanprodan** [comment]
This would be addressed for OCI charts when we implement:
- https://github.com/fluxcd/helm-controller/issues/789
- https://github.com/fluxcd/source-controller/issues/1391
