### ISSUE TITLE
[BUG] Helm drift detection on configmap patching '*** (after)' instead of the actual template from the helm chart

### ISSUE THREAD

**Issue by soumyabk** [fluxcd/helm-controller#925]
Hi Folks, 
we're running helmcontroller version v0.37.2 and enabled drift detection. Noticing that if any manual change was added to one of the configmaps of our helm chart, the helm controller detects a drifts and patches with a string and not the actual config map from the helm template.
```
{"level":"debug","ts":"2024-03-26T00:16:19.027Z","msg":"resource modified","controller":"helmrelease","controllerGroup":"helm.toolkit.fluxcd.io","controllerKind":"HelmRelease","HelmRelease":{"name":"<resource_name>","namespace":"flux-system"},"namespace":"flux-system","name":"<servicename>","reconcileID":"94f4e548-7273-44b3-a316-859516ec5dbe","resource":"ConfigMap/flux-system/<service>-config","patch":[{"value":"*** (after)","op":"replace","path":"/data/config.yaml"}]}
```
Config map after reconcile:
```
apiVersion: v1
data:
  config.yaml: '*** (after)'
kind: ConfigMap
metadata:
********
```
configmap template sample:
```
apiVersion: v1
data:
  config.yaml: |
    slaPeriod: 12h   # if this is manually updated to 6h, then drift detection runs
metadata:
********
```
the helmrelease also seems to be stuck with `ProgressingWithRetry`
```status:
  conditions:
  - lastTransitionTime: "2024-03-28T00:37:54Z"
    message: Helm upgrade succeeded for release flux-system/<chart_name>.v53 with chart <chart_name>@0.0.5
    observedGeneration: 21
    reason: ProgressingWithRetry
    status: "True"
    type: Reconciling
```

**Comment by soumyabk** [comment]
also another thing we noticed, using the annotation `helm.toolkit.fluxcd.io/driftDetection: disabled` does not skip the resource from being patched wrongly:

**Comment by souleb** [comment]
There have been many changes in the underlying package that perform all the drift and apply between `v0.37.2` and `v0.37.4`. Can you test this on the last version?

**Comment by souleb** [comment]
> Another thing we noticed, using the annotation helm.toolkit.fluxcd.io/driftDetection: disabled does not skip the resource from being patched wrongly:

Are you setting it up manually or as part of the helmChart?

**Comment by soumyabk** [comment]
> There have been many changes in the underlying package that perform all the drift and apply between `v0.37.2` and `v0.37.4`. Can you test this on the last version?

Seeing the problem even after upgrading to v0.37.4
```
✗ flux version
flux: v2.2.3
helm-controller: v0.37.4
✗ kubectl -n <namespace> get configmaps <service-name>-config -o=jsonpath='{.data}'
{"config.yaml":"*** (after)"}%
```

**Comment by soumyabk** [comment]
> > Another thing we noticed, using the annotation helm.toolkit.fluxcd.io/driftDetection: disabled does not skip the resource from being patched wrongly:
> 
> Are you setting it up manually or as part of the helmChart?

we set the annotation on the resource manually, but we see the annotation even after helm reconciles it with the wrong patch
```
(⎈|nd-sjc6dd)➜  jenkins-pipeline-shared-lib git:(pika) ✗ k -n pika-system get configmaps pika-config -o yaml

apiVersion: v1
data:
  config.yaml: '*** (after)'
kind: ConfigMap
metadata:
  annotations:
    helm.toolkit.fluxcd.io/driftDetection: disabled
    meta.helm.sh/release-name: <chart-name>
    meta.helm.sh/release-namespace: flux-system
  creationTimestamp: "2024-01-25T09:19:13Z"
  labels:
    app: <chart-name>
    app.kubernetes.io/managed-by: Helm
    helm.toolkit.fluxcd.io/name: <chart-name>
    helm.toolkit.fluxcd.io/namespace: flux-system
  name: <chart-name>-config
  namespace: <chart-name>-system
  resourceVersion: "912413821"
  uid: 496b9d65-919b-4f21-a4e3-58070514ea73
```

**Comment by soumyabk** [comment]
Also `flux reconcile helmrelease --force` does not seem to be able to fix the helmrelease once its stuck in `ProgressingWithRetry` status.

**Comment by soumyabk** [comment]
thanks @souleb. When is the next version of the helm-controller release expected, so we can pick up this fix.

**Comment by stefanprodan** [comment]
@soumyabk see https://github.com/fluxcd/flux2/issues/4712

**Comment by soumyabk** [comment]
Also, can you confirm what is the right way to get helm-reconcile to ignore specific resources. I had tried adding this annotation `helm.toolkit.fluxcd.io/driftDetection: disabled` and also using the `driftDetection.ignore` field in the helmrelease and in both situations, the drift detection tried to patch the resource
```
  driftDetection:
    ignore:
    - paths:
      - data/
      target:
        kind: configmap
        name: <chart-name>-config
    mode: enabled
```

**Comment by stefanprodan** [comment]
It's `kind: ConfigMap`

**Comment by stefanprodan** [comment]
Also json paths must begin with `/` instead of ending with it. See here the docs: https://fluxcd.io/flux/components/helm/helmreleases/#ignore-rules

Should be:

```yaml
  driftDetection:
    ignore:
      - paths: ["/data"]
        target:
          kind: ConfigMap
```

**Comment by soumyabk** [comment]
thanks that worked. Also, what is the recommended way to use  this label `helm.toolkit.fluxcd.io/driftDetection: disabled` - can it be patched manually on some resource we want to temporarily disable on a cluster to test/debug something or does it need to come as a kustomization patch.

**Comment by stefanprodan** [comment]
@soumyabk you’ll be able to annotate objects in-cluster after Flux 2.3 release.
