### ISSUE TITLE
Flux Helm Not Removing HPA objects on upgrade

### ISSUE THREAD

**Issue by LukeRH** [fluxcd/helm-controller#993]
Hi,
We are seeing an issue where if we remove a HPA object from the helm chart in a new release this is not removed when the Helm upgrade is performed by Flux. 

![image](https://github.com/fluxcd/helm-controller/assets/17493218/d01722c9-b3c0-43a5-aa09-b9ad6083e459)

![image](https://github.com/fluxcd/helm-controller/assets/17493218/c2ecf9de-d21f-411f-82f1-a789587f793d)

Is this expected behaviour? if so what is the recommended way to reconcile the helm chart?

Thanks

flux: v2.2.3
distribution: flux-v2.2.3
helm-controller: v0.37.4
image-automation-controller: v0.37.1
image-reflector-controller: v0.31.2
kustomize-controller: v1.2.2
notification-controller: v1.2.4
source-controller: v1.2.4

**Comment by souleb** [comment]
Hello, are you sure that the new version has been picked up by Flux?  Can you provide an example of your in-cluster CRs?
